version: 2
jobs:
  build-test: 
    docker: 
      - image: ubuntu:20.04
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update && apt-get install -y \
              git \
              libboost-dev \
              autotools-dev \
              swig \
              python3 \
              python3-dev \
              libgdal-dev \
              pkg-config \
              gcc \
              openjdk-11-jdk \
              build-essential \
              libosmium2-dev \
              libgumbo-dev \
              libwebkit2gtk-4.0-dev \
              libopenmpi-dev \
              libboost-all-dev \
              librange-v3-dev \
              dejagnu \
              wget \
              unzip \
              libxml++2.6-dev && rm -rf /var/lib/apt/lists/*
            mkdir /libpqxx && cd /libpqxx
            wget https://github.com/jtv/libpqxx/archive/7.3.1.zip && \
              unzip 7.3.1.zip && \
              cd libpqxx-7.3.1/
            ./configure --enable-shared
            make
            make install
      - checkout
      - run:
          name: Install Underpass
          command: |
            echo $PKG_CONFIG_PATH
            rm -rf /libpqxx && \
              ln -s /lib/x86_64-linux-gnu/pkgconfig/python-3.8.pc /lib/x86_64-linux-gnu/pkgconfig/python.pc
            ./autogen.sh
            mkdir build
            cd build && ../configure
            make
          environment: 
            PKG_CONFIG_PATH: "/root/project/m4/" # todo: properly ref this
      - run:
          name: Run tests
          command: cd build && make check
workflows:
  version: 2
  test-deploy:
    jobs:
      - build-test
      # - deploy-staging
