name: default
on:
   push:
jobs:
   build:
      runs-on: fedora-latest
      steps:
	- uses: actions/doxygen-action@v1
	- run: ./configure
with:
    working-directory: '.'
    doxyfile-path: 'docs/'

