name: 🧪 Build and Test

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Start Docker Compose
        run: cd docker && docker-compose up -d

      - name: Build Underpass Library and Binaries
        run: docker-compose -f docker/docker-compose.yml exec -T underpass-build-deps sh -c "cd /code && ./autogen.sh && mkdir build && cd build && ../configure && make -j `nproc`"

      - name: Build and Run Underpass Tests (broken - it never fails)
        run: docker-compose -f docker/docker-compose.yml exec -T underpass-build-deps sh -c "cd /code/build && make check -j `nproc`"

      # Workaround for broken make check which never fails: run the tests manually
      - name: Run Test val-test
        run: docker-compose -f docker/docker-compose.yml exec -T underpass-build-deps sh -c "cd /code/build && testsuite/libunderpass.all/val-test"

      - name: Run Test tm-test
        run: docker-compose -f docker/docker-compose.yml exec -T underpass-build-deps sh -c "cd /code/build && testsuite/libunderpass.all/tm-test"

      - name: Run Test usersync-test
        run: docker-compose -f docker/docker-compose.yml exec -T underpass-build-deps sh -c "cd /code/build && testsuite/libunderpass.all/usersync-test"

