name: 🧪 Build and Test

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Start Docker Compose
        run: cd docker && docker-compose up -d

      - name: Prepare Test Database
        run: docker-compose -f docker/docker-compose.yml exec -T postgis psql -U underpass_test -f /code/ci/create_underpass_db.sql

      - name: Build Underpass Library and Binaries
        run: docker-compose -f docker/docker-compose.yml exec -T underpass-build-deps sh -c "cd /code && ./autogen.sh && mkdir build && cd build && ../configure && make -j `nproc`"

      - name: Build and Run Underpass Tests
        run: docker-compose -f docker/docker-compose.yml exec -T underpass-build-deps sh -c "cd /code/build && make check -j `nproc`"

